name: Compile and Run w32_gl.h tests
on: [push, pull_request]

jobs:
  windows:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Compile types tests
        run: ${{ matrix.cc }} -O2 -std=c89 -pedantic -Wall -Wextra -Werror -Wvla -Wconversion -Wdouble-promotion -Wsign-conversion -Wuninitialized -Winit-self -Wunused -Wunused-macros -Wunused-local-typedefs -o w32_gl_test_${{ matrix.cc }}.exe tests/w32_gl_test.c
      - name: Run types tests
        run: .\w32_gl_test_${{ matrix.cc }}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-latest-${{ matrix.cc }}-w32_gl_test
          path: w32_gl_test_${{ matrix.cc }}.exe
